---
name: testing dummy CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-18.04
    steps:
      - name: Run dummy test
        run: echo "I exist to be Required in Github branch protection rules"
